#+TITLE: Polybar Config
#+PROPERTY:

* Table of Contents :toc:
- [[#about][About]]
- [[#bspwm_setup][bspwm_setup]]
  - [[#description-bspwm][Description bspwm]]
- [[#theme][Theme]]

* About
I mostly use linux as my development Operating System. The only purpose of this repo is that
I want my configuration to be uploaded/saved on internet somewhere safe so that I can use it
whenever need in my new system.

Currently using Arch Linux (bspwm) and this configuration works fine for me.
I have also changed some of the default configuration in the bspwm section in the config file.

* bspwm_setup
These are the setting in my bspwm section in the polybar config file.

#+BEGIN_SRC

[bar/mainbar-bspwm]
monitor = ${env:MONITOR}
;monitor-fallback = HDMI1
width = 100%
height = 30
;offset-x = 1%
;offset-y = 1%
radius = 0.0
fixed-center = true
bottom = false
separator = |

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2
line-color = #f00

wm-restack = bspwm
override-redirect = true

; Enable support for inter-process messaging
; See the Messaging wiki page for more details.
enable-ipc = true

border-size = 3
border-left-size = 20
border-right-size = 20
;border-top-size = 0
;border-bottom-size = 25
border-left-color = #00000000
border-right-color = #00000000
border-color = #0099ff
padding-left = 0
padding-right = 0

module-margin-left = 3
module-margin-right = 3

;https://github.com/jaagr/polybar/wiki/Fonts
font-0 = "Noto Sans:size=10;0"
font-1 = "FontAwesome:size=13;0"
font-2 = "Noto Sans:size=10;0"
font-3 = "Noto Sans Mono:size=10;0"

modules-left = bspwm xwindow
modules-center = kernel
modules-right = pavolume memory2 cpu2 date

tray-detached = false
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 2
tray-maxsize = 20
tray-scale = 1.0
tray-position = right
tray-background = ${colors.background}

scroll-up = bspwm-desknext
scroll-down = bspwm-deskprev


#+END_SRC


** Description bspwm

#+BEGIN_SRC
border-size = 3               ;set border around the polybar
#+END_SRC


#+BEGIN_SRC
;Set the border size to the left and right of the polybar similar to my windows
border-left-size = 20
border-right-size = 20
#+END_SRC


#+BEGIN_SRC
;Below I have set the color of the border 
border-color = #0099ff
;In the left and right border I have set the color to transparent 
border-left-color = #00000000
border-right-color = #00000000
#+END_SRC

* Theme
I am using Gotham theme of polybar with some transparency.
#+BEGIN_SRC
; Gotham theme ==========
 background = #77000000
 foreground = #ff40ff00
 alert = #d26937
 volume-min = #2aa889
 volume-med = #edb443
 volume-max = #c23127
; ======================
#+END_SRC




;=====================================================
;
;   To learn more about how to configure Polybar
;   go to https://github.com/jaagr/polybar
;
;   The README contains alot of information
; 	Themes : https://github.com/jaagr/dots/tree/master/.local/etc/themer/themes
;   https://github.com/jaagr/polybar/wiki/
;   https://github.com/jaagr/polybar/wiki/Configuration
;   https://github.com/jaagr/polybar/wiki/Formatting
;
;=====================================================
